# -*- coding: utf-8 -*-
'''
create and install configuration profiles.

 .. code-block:: yaml

    com.example.profileidentifier:
        profile:
            - installed
            - description: This description is shown underneath the display name
            - displayname: Salt-OSX Example Profile
            - organization: Salt-OSX Inc.
            - removaldisallowed: False
            - content:
                ...

'''
import logging
import salt.utils
import salt.exceptions


log = logging.getLogger(__name__)
__virtualname__ = 'profile'


def __virtual__():
    return __virtualname__ if salt.utils.is_darwin() else False


def installed(name, description, displayname, organization, removaldisallowed, content):
    '''
    Create and install the specified configuration profile, using the supplied payload content.
    This state module is not intended to be used at the command line.

    name:
        The name of the resource is the payload identifier, which is used to determine whether the payload is
        installed.

    description:
        Description shown below profile name in profile preferences.

    displayname:
        The main title shown that identifies the profile.

    organization:
        The organization responsible for creating the profile.

    removaldisallowed:
        Whether or not to disallow removal of this profile.

    content:
        The payload data contained within this profile. Should be generated by another formula.
    '''
    ret = {'name': name,
           'result': True,
           'changes': {},
           'comment': ''}

    installed = __salt__['profile.installed'](name)

    if __opts__['test']:
        if installed:
            ret['comment'] = 'Profile already installed with identifier: {0}'.format(name)
            return ret

        content = __salt__['profile.generate'](
            name,
            description,
            displayname,
            organization,
            content
        )

        ret['result'] = None
        ret['comment'] = 'New profile would have been generated, property list follows: {0}'.format(content)
        return ret

    raise salt.exceptions.CommandNotFoundError(
        'This functionality does not yet exist! profiles can only be run in test mode'
    )